### ISSUE TITLE
最终录制的视频没有声音

### ISSUE THREAD

**Issue by allen8300** [kaifeng123/NatCorder#3]
Kaifeng老师您好，请教下：
这里我尝试了您的demo，其它都是没有问题的，除了最终的视频没有声音；
引入MP3文件后，尝试了很多方法，最终都没有声音；求指教

**Comment by kaifeng123** [comment]
https://blog.csdn.net/f_957995490/article/details/109789771
你看一下这个吧,这是我之前项目弄的这个,最后也没立项

**Comment by kaifeng123** [comment]
> 开封老师您好，请教下： 这里我试验了您的演示，其他没有问题的，除了最终的声音；引入 MP3文件后，尝试了很多方法，最终都没有；求指教

https://blog.csdn.net/f_957995490/article/details/109789771
你看看这个吧，我项目弄的这个，最后也没立项

**Comment by kaifeng123** [comment]
> 亲爱的老师👍方便加个微信么，更方便些，18301546656

应该是可以录声音的,你看一下是不是权限没开那些的,我现在换苹果手机了,也没办法帮你测试的

**Comment by allen8300** [comment]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/1751906/157030550-65bebc55-61cf-4bba-b3af-7b40e5286904.png">
我把61行，提前到57行，就可以录到音频了；

原本为什么要放到61行呢？

**Comment by kaifeng123** [comment]
> <img alt="图片" width="833" src="https://user-images.githubusercontent.com/1751906/157030550-65bebc55-61cf-4bba-b3af-7b40e5286904.png">
> 
> 我把61行，提前到57行，就可以录到音频了；
> 原来为什么要另外61行呢？

忘了，大佬厉害啊

**Comment by allen8300** [comment]
啊 老师才是大佬🙏🏻哈哈，感恩；方便的话，可以加个微信常交流👍
